variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - prepare_develop_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    only:
      variables:
        - $version
    script:
        - export TZ="Asia/Taipei"
        - export PKG_FW_VERSION=${version}
        - export PKG_BUILDDATE=$(date +%y%m%d%H)
        - dpkg --add-architecture amd64
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20190909/ stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - dpkg-buildpackage -us -uc -b -aamd64
        - echo "The package firmware version=${PKG_FW_VERSION}"
        - echo "The package build date=${PKG_BUILDDATE}"
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - stretch/master
      variables:
        - $version
    dependencies:
        - develop_build
    when: manual
    script:
        - mkdir -p /cache/stretch/develop/
        - cp *.deb /cache/stretch/develop/
        - ls /cache/stretch/develop/
