#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
#       2019    Remus TY Wu <remusty.wu@moxa.com>
#

platform_initial() {
	:
}

platform_stop() {
	:
}

case "$1" in
start)
	platform_initial
	;;
restart | reload | force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
stop)
	platform_stop
	;;
*)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

exit 0
